language: go

go:
  - 1.7.3

# let us have speedy Docker-based Travis workers
sudo: false

before_script:
  - ci/travis_etcd.sh 3.0.12
#  - ci/travis_zk.sh 3.5.1-alpha

install:
  - go get -t -d ./...
  - go get github.com/golang/lint/golint
  - go get github.com/mattn/goveralls
  - go get github.com/GeertJohan/fgt
  - cd $GOPATH/src/github.com/coreos/etcd; git checkout release-3.0; cd -
  - cd $GOPATH/src/google.golang.org/grpc; git checkout 71d2ea4f75286a63b606aca2422cd17ff37fd5b8; cd -

script:
  - ./etcd/etcd --listen-client-urls 'http://0.0.0.0:2379' --advertise-client-urls 'http://127.0.0.1:2379' >/dev/null 2>&1 &
  - sleep 5
  - echo very-secure|ETCDCTL_API=3 ./etcd/etcdctl --endpoints=[localhost:2379] user add --interactive=false test
#  - ./zk/bin/zkServer.sh start ./zk/conf/zoo.cfg 1> /dev/null
  - ci/validate-gofmt
  - go vet ./...
  - fgt golint ./...
  - go test -v -race ./...
  - ci/coverage
  - goveralls -service=travis-ci -coverprofile=goverage.report
