language: go

go:
  - 1.6.2

# let us have speedy Docker-based Travis workers
sudo: false

before_script:
  - script/travis_etcd.sh 3.0.0
  - script/travis_zk.sh 3.5.1-alpha

script:
  - ./etcd/etcd --listen-client-urls 'http://0.0.0.0:2379' --advertise-client-urls 'http://127.0.0.1:2379' >/dev/null 2>&1 &
  - ./zk/bin/zkServer.sh start ./zk/conf/zoo.cfg 1> /dev/null
  - script/validate-gofmt
  - go vet ./...
  - fgt golint ./...
  - go test -v -race ./...
  - script/coverage
  - goveralls -service=travis-ci -coverprofile=goverage.report
